
create_tmux:
	tmux new -s unseen_model -d 'python run_occupation_covariate.py'

reattach_tmux:
	tmux attach-session -t unseen_model

kill_session:
	tmux kill-session -t unseen_model

monitor_session:
	tmux ls

save_logs:
tmux capture-pane -t unseen_model -p > server_log.txt


# to leave: Press Ctrl + b (release both keys), then press d